import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Auto-generated by FlutterFire CLI
import 'home_screen.dart';
import 'login_screen.dart';

void main() async {
  // Step 1: Required before any async operations in main()
  // Flutter needs to be initialized before we can use platform channels
  WidgetsFlutterBinding.ensureInitialized();
  // Step 2: Initialize Firebase using the auto-generated config
  // This must complete before the app starts
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  // Step 3: Now it is safe to launch the app
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Cloud Clipboard',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
      ),
      // Instead of home: LoginScreen(), we use a StreamBuilder
      // This automatically routes to the correct screen
      home: StreamBuilder<User?>(
        stream: FirebaseAuth.instance.authStateChanges(),
        builder: (context, snapshot) {
        // snapshot.hasData is true when a user is logged in
        if(snapshot.hasData) {
          return const HomeScreen(); // User IS logged in
        }
          return const LoginScreen(); // User is NOT logged in
        },
      ),
    );
  }
}